In [5]:
# Задание 1

import numpy as np

N=10
print('{}'.format(np.arange(N-1, -1,-1)))


[9 8 7 6 5 4 3 2 1 0]


In [6]:
# Задание 2

N=int(input())
sum=np.diag(np.arange(N-1, -1, -1)) 
print(sum)

4
[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]


In [12]:
# Задание 3
"""
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""

from numpy import linalg

a=np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [2]:
# Задание 4, Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем
import numpy as np
from numpy import dot

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

# На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

# Найдите самого похожего пользователя. Посчитайте косинусное сходство между этим пользователем и всеми поль-ями из массива user_stats

def cosine( users_stats, next_user_stats ):
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )

search = np.array([cosine(row, next_user_stats) for row in users_stats])
best_user = np.argmax(search)
print(best_user)


7
